print("1. True and True.\n\tYou: True, Answer: ", True and True)
print("2. False and True.\n\tYou: False, Answer: ", False and True)
print("3. 1 == 1 and 2 == 1.\n\tYou: False, Answer: ", 1 == 1 and 2 == 1)
print("4. \"test\" == \"test\".\n\tYou: True, Answer: ", "test" == "test")
print("5. 1 == 1 or 2 != 1.\n\tYou: True, Answer: ", 1 == 1  or 2 != 1)
print("6. True and 1 == 1.\n\tYou: True, Answer: ", True and 1 == 1)
print("7. False and 0 != 0.\n\tYou: False, Answer: ", False and 0 != 0)
print("8. True or 1 == 1.\n\tYou: True, Answer: ", True or 1 == 1)
print("9. \"test\" == \"testing\".\n\tYou: False, Answer: ", "test" == "testing")
print("10. 1 != 0 and 2 == 1.\n\tYou: False, Answer: ", 1 != 0 and 2 == 1)
print("11. \"test\" != \"testing\".\n\tYou: True, Answer: ", "test" != "testing")
print("12. \"test\" == 1.\n\tYou: False, Answer: ", "test" == 1)
print("13. not (True and False).\n\tYou: True, Answer: ", not(True and False))
print("14. not (1 == 1 and 0 != 1).\n\tYou: False, Answer: ", not (1 == 1 and 0 != 1))
print("15. not (10 == 1 or 10000 == 1000).\n\tYou: True, Answer: ", not (10 == 1 or 10000 == 1000))
print("16. not ( 1 != 10 or 3 == 4).\n\tYou: False, Answer: ", not ( 1 != 10 or 3 == 4))
print("17. not(\"testing\" == \"testing\" and \"Zed\" == \"Cool Guy\").\n\tYou: True, Answer: ", not("testing" == "testing" and "Zed" == "Cool Guy"))
print("18. 1 == 1 and (not(\"testing\" == 1 or 1 == 0)) and True.\n\tYou: True, Answer: ", 1 == 1 and (not("testing" == 1 or 1 == 0)))
print("19. \"chunky\" == \"bacon\" and (not (3 == 4 or 3 == 3)).\n\tYou: False, Answer: ", "chunky" == "bacon" and (not (3 == 4 or 3 == 3)))
print("20. 3 == 3 and (not(\"testing\" == \"testing\" or \"Python\" == \"Fun\")).\n\tYou: False, Answer: ", 3 == 3 and (not("testing" == "testing" or "Python" == "Fun")))